Models/Documento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.detalle = new HashSet<detalle>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string cedula { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle> detalle { get; set; }
    }
}

Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaEntities : DbContext
    {
        public PruebaEntities()
            : base("name=PruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle> detalle { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
    }
}

Models/Model1.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\santi\Desktop\Test\Prueba\Prueba\Models\Model1.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Models/ViewsModels/DocumentoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Prueba.Models.ViewsModels
{
    public class DocumentoViewModel
    {
        public string Cedula { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }

        public List<Detalle> detalles { get; set; }

    }

    public class Detalle
    {
        public string Codigo { get; set; }
        public string NombreCuenta { get; set; }
        public decimal Debito { get; set; }

        public decimal Credito { get; set; }
    }
}

Models/detalle.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id { get; set; }
        public int idDocumento { get; set; }
        public string codigo { get; set; }
        public string nombreCuenta { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prueba.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/MaestroDetalleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prueba.Models.ViewsModels;
using Prueba.Models;
namespace Prueba.Controllers
{
    public class MaestroDetalleController : Controller
    {
        // GET: MaestroDetalle
        public ActionResult Add()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult Add(DocumentoViewModel model)
        {
            try
            {
                using (PruebaEntities db = new PruebaEntities())
                {
                    Documento doc = new Documento();
                    doc.fecha = DateTime.Now;
                    doc.cedula = model.Cedula;
                    doc.descripcion = model.Descripcion;
                    doc.nombre = model.Nombre;
                    db.Documento.Add(doc);
                    db.SaveChanges();

                    foreach (var i in model.detalles)
                    {
                        detalle oDetalle = new detalle();
                        oDetalle.codigo = i.Codigo;
                        oDetalle.nombreCuenta = i.NombreCuenta;
                        oDetalle.debito = i.Debito;
                        oDetalle.credito = i.Credito;
                        oDetalle.idDocumento = doc.id;
                        db.detalle.Add(oDetalle);

                        
                    }
                    db.SaveChanges();


                }
                ViewBag.Message = "Venta registrada correctamente";
                return View();
            }
            catch (Exception ex)
            {
                return View(model);
            }
            

        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/MaestroDetalle/Add.cshtml
@model Prueba.Models.ViewsModels.DocumentoViewModel
@{
    ViewBag.Title = "Aplication MVC Maestro Detalle";
}

<h2>@ViewBag.Title</h2>

<div style="color:#4cff00">
    @ViewBag.Message
</div>
@using (Html.BeginForm("Add", "MaestroDetalle", FormMethod.Post))
{

    <div class="row ">
        <div class="form-group">
            @Html.LabelFor(d => d.Cedula)
            @Html.TextBoxFor(d => d.Cedula)
            @Html.LabelFor(d => d.Descripcion)
            @Html.TextBoxFor(d => d.Descripcion)
            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre)
        </div>

    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Codigo">Codigo</label>
                <input class="form-control" type="text" id="Codigo" />
            </div>
            <div class="form-group">
                <label for="NombreCuenta">Nombre Cuenta</label>
                <input class="form-control" type="text" id="NombreCuenta" />
            </div>
            <div class="form-group">
                <label for="Debito"> Debito</label>
                <input class="form-control" type="text" id="Debito" onclick="clearCredit()" />
            </div>
            <div class="form-group">
                <label for="Credito"> Credito</label>
                <input class="form-control" type="text" id="Credito" onclick="clearDebit()" />
            </div>

            <div class="form-group">
                <button class="btn btn-primary mt-5" onclick="create(); return false;">Agregar</button>
            </div>
        </div>
    </div>
    <div id="divConceptos">
        <table class="table" id="tablaConceptos">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Nombre Cuenta</th>
                    <th>Debito</th>
                    <th>Credito</th>
                    
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <div class="form-group mt-5">
        <input class="btn btn-primary" type="submit" value="Guardar" />
       
    </div>
  

   
    <script>
        var num = 0;

        function CreateTableCell(value) {
            const td = document.createElement('td');
            td.innerHTML = value;
            return td;

        }
        function CreateHiddenInput(name, value) {
            const input = document.createElement('input');
            input.name = name;
            input.value = value;
            input.type = 'hidden';

            return input;
        }
        function CreateRow(Codigo,nombreCuenta,Debito,Credito) {
        const tr = document.createElement('tr');
        const tdCodigo = CreateTableCell(Codigo);
        const tdNombreCuenta = CreateTableCell(nombreCuenta);
        const tdDebito = CreateTableCell(Debito);
        const tdCredito = CreateTableCell(Credito);

            tr.appendChild(tdCodigo);
            tr.appendChild(tdNombreCuenta);
            tr.appendChild(tdDebito);
            tr.appendChild(tdCredito);

            return tr;

        }
        function AddConceptos(Codigo, nombreCuenta, Debito, Credito) {

            const table = document.getElementById('tablaConceptos');
            const row = CreateRow(Codigo, nombreCuenta, Debito, Credito);
            table.appendChild(row);

        }
        function AddDivConceptos(Codigo, nombreCuenta, Debito, Credito) {
            const divConceptos = document.getElementById('divConceptos');
            const hiddenIndex = CreateHiddenInput("detalles.Index", num);
            const hiddenCodigo = CreateHiddenInput("detalles[" + num + "].Codigo", Codigo);
            const hiddenNombreCuenta = CreateHiddenInput("detalles[" + num + "].NombreCuenta", nombreCuenta);
            const hiddenDebito = CreateHiddenInput("detalles[" + num + "].Debito", Debito);
            const hiddenCredito = CreateHiddenInput("detalles[" + num + "].Credito", Credito);


            divConceptos.appendChild(hiddenIndex);
            divConceptos.appendChild(hiddenCodigo);
            divConceptos.appendChild(hiddenNombreCuenta);
            divConceptos.appendChild(hiddenDebito);
            divConceptos.appendChild(hiddenCredito);

           

        }

        function clearInputs() {
            document.getElementById('Codigo').value = '';
            document.getElementById('NombreCuenta').value = '';
            document.getElementById('Debito').value = '';
            document.getElementById('Credito').value = '';
        }

        function create() {
            const Codigo = document.getElementById('Codigo').value;
            const nombreCuenta = document.getElementById('NombreCuenta').value;
            const Debito = document.getElementById('Debito').value;
            const Credito = document.getElementById('Credito').value;

            AddConceptos(Codigo, nombreCuenta, Debito, Credito);
            AddDivConceptos(Codigo, nombreCuenta, Debito, Credito);
            clearInputs();
            num++;

           
            const debitInput = document.getElementById('Debito');
            const creditInput = document.getElementById('Credito');
            debitInput.disabled = false;
            creditInput.disabled = false;
        }
        function clearDebit() {
            const debitInput = document.getElementById('Debito');
            const creditInput = document.getElementById('Credito');
            debitInput.value = '0';
            debitInput.disabled = true;
            creditInput.value = '';
            creditInput.disabled = false;
        }

        function clearCredit() {
            const creditInput = document.getElementById('Credito');
            const debitInput = document.getElementById('Debito');
            creditInput.value = '0';
            creditInput.disabled = true;
            debitInput.value = '';
            debitInput.disabled = false;
        }
       

         

     


        
    </script>










}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>